GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6255303fef80639008d3e80d
###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
"name" : "hammas",
"subscriberToChannel" : "hammas 576 "

}

###

DELETE http://localhost:3000/subscribers/6255353f81211905ff3f5594

###

PATCH http://localhost:3000/subscribers/6255353f81211905ff3f5594
Content-Type: application/json

{
    "name": "new name "
}